# Renders the "Sponsor" button on the repository and in issue sidebars.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [uoparaji]
